### ISSUE TITLE
Bug when run script tsup-build-stages.ts

### ISSUE THREAD

**Issue by nguyenthanhan201** [tigawanna/shadcn-ui-fanedition#4]
<img width="578" alt="Screenshot 2023-12-27 at 11 34 11" src="https://github.com/tigawanna/shadcn-ui-fanedition/assets/80932055/a74ff49d-cc31-4cf6-aa59-750125b488d5">

When a chunk item has only 1 item, will build a component without a folder so I can not import multiple entries with that component

Order chunk with 3 items when build will have folder of that components
<img width="599" alt="Screenshot 2023-12-27 at 11 38 49" src="https://github.com/tigawanna/shadcn-ui-fanedition/assets/80932055/8a1fb510-b6c9-4d10-8ae8-fb839a1f8b23">

**Comment by nguyenthanhan201** [comment]
thank you for your help

**Comment by tigawanna** [comment]
I haven't worked on this for a while am considering taking it down since I ran into some bundling config limitations that I didn't get any help on

**Comment by nguyenthanhan201** [comment]
thank you for your help
